version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-secret-key-here-change-in-production
      - TOKEN_EXPIRY=24h
    volumes:
      - ./config:/root/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Uncomment the following when you're ready to add a database
  # db:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=auth_service
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  
  # Uncomment the following when you're ready to add Redis for token blacklisting
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

# Uncomment when you're ready to use volumes
# volumes:
#   postgres_data:
#   redis_data: