version: '3'

services:
  auth-service:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
    command: go run cmd/server/main.go

  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: auth
  #     POSTGRES_PASSWORD: auth
  #     POSTGRES_DB: auth
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: