name: Go Auth Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./cmd/server

    - name: Test
      run: go test -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t go-auth-service .
      
    - name: Test Docker image
      run: |
        docker run -d -p 8080:8080 --name test-container go-auth-service
        sleep 5
        curl -s --retry 10 --retry-connrefused http://localhost:8080/
        docker stop test-container