name: Go Auth Service CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download

    - name: Build
      run: go build -v ./cmd/server

    - name: Test
      run: go test -v ./...

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        # Store the tag in a variable so we use the same one for both steps
        IMAGE_TAG=$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag go-auth-service:$IMAGE_TAG
      
    - name: Test Docker image
      run: |
        docker run --name auth-test -d -p 8080:8080 go-auth-service:${{ env.IMAGE_TAG }}
        sleep 5
        curl -f http://localhost:8080/health || exit 1