name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  memory-tests:
    name: In-Memory Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Run in-memory integration tests
      run: go test -v ./internal/integration/memory_auth_test.go
      env:
        JWT_SECRET: test-secret-key
        TOKEN_EXPIRY: 1h

  database-tests:
    name: Database Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: auth_service_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...
      
    - name: Run database integration tests
      run: go test -tags=database -v ./internal/integration/db_auth_test.go
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: auth_service_test
        DB_SSLMODE: disable
        JWT_SECRET: test-secret-key
        TOKEN_EXPIRY: 1h
